# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('courseload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='favorites',
            field=models.ManyToManyField(related_name='userfaves', to='login_app.User'),
        ),
    ]
